Repository untoc-camp/loopy_friends, pull requests merged in 2024-04, with the labels that each got.

#2 레이아웃 작성
  .vscode/settings.json
  analysis_options.yaml
  lib/components/bottom_navigation/bottom_navigation.dart
  lib/components/bottom_navigation/bottom_navigation_bar_controller.dart
  lib/layout/main_layout.dart
  lib/router/main_rotuer.dart
  lib/view/main_page_view.dart
  pubspec.yaml
Labels: Feature

#7 텍스트수정
  lib/view/main_page_view.dart
Labels: Design

#10 플러터 버전 변경
  pubspec.lock
  pubspec.yaml
Labels: bug

#12 사이드 바 적용 (수정 필요)
  lib/layout/main_layout.dart
  pubspec.lock
  pubspec.yaml
Labels: Feature

#13 사이드 바 제작
  lib/components/side_Bar/side_bar.dart
  lib/components/side_Bar/side_bar_controller.dart
  lib/layout/main_layout.dart
  pubspec.lock
  pubspec.yaml
Labels: Feature
